### ISSUE TITLE
aurelia.use.globalResources() fails, can't find the module

### ISSUE THREAD

**Issue by nashwaan** [nathanchase/super-minimal-aurelia#3]
I tried to use `globalResources()` but the browser gives this error:
`Unhandled rejection Error: Unable to find module with ID: ./my-element`

Here are the things I did:

main.js:
```js
import {Aurelia, PLATFORM} from 'aurelia-framework';
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .globalResources('./my-element') // <--- added this line
  aurelia.start().then(() => aurelia.setRoot(PLATFORM.moduleName('app')));
}
```

src/my-element.html:
```html
<template>
    <div>Hi ${name}</div>
</template>
```

src/my-element.js:
```js
export class MyElementCustomElement {
    constructor() {
        this.name = 'John';
    }
}

```

src/app.html:
```html
<template>
  <my-element></my-element>  // <---- added this line
  <h2>Aurelia + Webpack</h2>
  <nav>
    Navigate to: <a route-href='route: hello'>Hello</a> | <a route-href='route: about'>About</a>
  </nav>
  <router-view></router-view>
</template>
```

As far as I know, `aurelia.use.globalResources()` is part of `aurelia-framework` package. Do I need to install additional packages for this minimal setup? Or is there something wrong with my code?

**Comment by nathanchase** [comment]
You have to use PLATFORM.moduleName. 

So it would be something like:

`.globalResources(PLATFORM.moduleName('./my-element'))`

From the wiki by @jods4:

> Here are a few common Aurelia APIs that take module names:
>
> * Routes { moduleId: "xxx" }
> * .plugin("xxx")
> * .feature("xxx") But see below!
> * .globalResources("xxx")
> * @useView("xxx")
> * .setRoot("xxx")
> All of those must be wrapped inside PLATFORM.moduleName("xxx").

See [https://github.com/jods4/aurelia-webpack-build/wiki/Managing-dependencies](https://github.com/jods4/aurelia-webpack-build/wiki/Managing-dependencies) for more info.

**Comment by nashwaan** [comment]
Wrapping module names with `PLATFORM.moduleName()` has fixed the issue. Thanks.

As this is a breaking change from `aurelia-webpack-plugin`, I suggest to put a note about this in README.md. Because all the current documentation in the web doesn't use `PLATFORM.moduleName()` yet.
