### ISSUE TITLE
<select> construct doesn't work in IE10

### ISSUE THREAD

**Issue by nashwaan** [nathanchase/super-minimal-aurelia#5]
I am not sure this is the right place to raise this issue but I am looking for help.

I did the following simple changes to `page-hello`

`page-hello.js`:

```js
export class PageHelloViewModel {
    products = ['Motherboard', 'CPU', 'Memory'];
    selectedProduct = '';
}
```

`page-hello.html`:
```html
<template>
  Select product:<br/>
  <select value.bind="selectedProduct">
    <option repeat.for="product of products" value.bind="product">${product}</option>
  </select>
  Selected product: ${selectedProduct}
</template>
```

This thing works for all browsers except for IE10-9.
The error in the console is obscure:
`ERROR [app-router] TypeError: Object doesn't support this action`

Any idea why `<select>` construct fails in IE10?

By the way, if I use radio buttons construct, it works in IE 11-9:
```html
<template>
  <label repeat.for="product of products">
    <input type="radio" name="group1" value.bind="product" checked.bind="selectedProduct">
    ${product}
  </label>
  Selected product: ${selectedProduct}
</template>
```

**Comment by nathanchase** [comment]
Hmm, not sure on this one. Maybe @jdanyow could help. He wrote the docs on `<select>` with Aurelia: http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-selects/1


This might be better resolved at [https://github.com/aurelia/binding/issues](https://github.com/aurelia/binding/issues)

**Comment by nashwaan** [comment]
Submitted an issue there  https://github.com/aurelia/binding/issues/584.

**Comment by nashwaan** [comment]
This is solved by doing the following:

Install MutationObserver:
```
npm install --save mutationobserver-shim
```

and added this line to `ie9-polyfill.js`:
```js
import 'mutationobserver-shim/MutationObserver'; // IE10 MutationObserver polyfill
import 'raf/polyfill'; // IE9 requestAnimationFrame polyfill
```

And now `<select>` construct works as expected in IE10-9.

**Comment by nashwaan** [comment]
@nathanchase You may want to include `MutationObserver` polyfill in this super-minimal-aurelia to support IE10-9.

**Comment by nashwaan** [comment]
@nathanchase I would also suggest to remove `Bluebird` promise from the list of dependencies and use the promise polyfill which is already included in `core-js`. Therefore, `new webpack.ProvidePlugin` becomes:

```js
    new webpack.ProvidePlugin({
        Map: 'core-js/es6/map',
        WeakMap: 'core-js/es6/weak-map',
        Promise: 'core-js/es6/promise',
    }),
```

Yes, `core-js/es6/promise` has less features than `bluebird`, but it is more in line with this repo objective: **minimal**.
😉

**Comment by nathanchase** [comment]
Sounds good to me! Do a PR and I'll merge it in.
