### ISSUE TITLE
Two issues in running webpack command

### ISSUE THREAD

**Issue by teemuniiranen** [nathanchase/super-minimal-aurelia#6]
With Mac OSX I got the following two errors:

### Aurelia Webpack Plugin 
```bash
TypeError: Cannot read property 'used' of null
    at processDependency (<mypath>/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:68:25)
```
Which was fixed by passing an object AureliaPlugin constructor in webpack.config.js:
new AureliaPlugin({ aureliaApp: undefined })

#### ie9-polyfill.js
Another issue is regarding to ie9-polyfill.js. I got the following error:
```bash
[181] ./ie9-polyfill.js 1.45 kB {0} [built] [failed] [1 error]
     + 450 hidden modules

ERROR in ./ie9-polyfill.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "<mypath>"
    at <mypath>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
```
Seems like there is missing dev dependency  babel-preset-es2015.

**Comment by nathanchase** [comment]
Not sure... Perhaps it's something to do with how OSX is organizing the node_modules dir? Are you using yarn or npm? I'd try deleting your node_modules folder and yarn.lock file and have it redownload everything again and see if the error goes away.

**Comment by teemuniiranen** [comment]
I am using yarn and adding babel-preset-es2015 fixed the issue.
