### ISSUE TITLE
Support for unit testing components using StageComponent

### ISSUE THREAD

**Issue by nashwaan** [nathanchase/super-minimal-aurelia#8]
Hi @nathanchase ,

Can you include a unit test example in this wonderful super minimal Aurelia + Webpack?

I tried but failed. Would appreciate to see how unit test using [StageComponent](http://aurelia.io/hub.html#/doc/article/aurelia/testing/latest/testing-components) can be incorporated in this minimal app.

**Comment by nathanchase** [comment]
Hmm, I'm not too adept yet at unit testing, either. I've been putting off unit testing for all my projects. :)

If you're able to integrate Jasmine + Karma successfully, and create a unit test, send a PR for it. I'd be interested to see that as well.

**Comment by nashwaan** [comment]
The latest update of the official [aurelia skeleton](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext-webpack) has fixed the issue of running `StageComponent` in webpack setup. The skeleton supports two testing envirnoments: jest and jasmine+karam.
